# Generated by Django 4.0 on 2021-12-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redmachine', '0002_commentcar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentCar',
        ),
    ]
