# Generated by Django 4.0 on 2021-12-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_dj', '0004_serial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
