# Generated by Django 4.0 on 2021-12-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
